/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Interview, UserProfile, RecentActivityItem, DocumentItem, InterviewerNote, Answer } from '../types';
import { STATUTORY_DOCUMENTS_CATALOGUE } from './questionsData';

export const INITIAL_CURRENT_USER: UserProfile = {
  id: 'usr-john-okello-001',
  email: 'john.okello@mglsd.go.ug',
  full_name: 'John Okello',
  role: 'interviewer',
  department_unit: 'Labour Directorate – TRANSFORMATIVE Programme',
  phone_number: '+256 772 458 912',
  avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
};

export const ADMIN_USER: UserProfile = {
  id: 'usr-admin-florence-002',
  email: 'florence.nsubuga@mglsd.go.ug',
  full_name: 'Florence Nsubuga',
  role: 'admin',
  department_unit: 'Policy, Planning & Modernisation Secretariat',
  phone_number: '+256 701 889 344',
  avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
};

export const INITIAL_INTERVIEWS: Interview[] = [
  {
    id: 'int-001',
    interviewee_name: 'Sarah Nansubuga',
    role_title: 'Permanent Secretary',
    department_unit: 'Ministry of Gender',
    years_in_role: 3.5,
    interview_date: '16 Sep 2025',
    interview_time: '10:15 AM',
    location: 'Kampala',
    interviewer_id: 'usr-john-okello-001',
    interviewer_name: 'John Okello',
    tier: 'Leadership',
    status: 'Completed',
    duration_min: 75,
    completion_percentage: 100,
    created_at: '2025-09-16T07:15:00Z',
    updated_at: '2025-09-16T08:30:00Z',
  },
  {
    id: 'int-002',
    interviewee_name: 'David Mukiibi',
    role_title: 'Director, Labour',
    department_unit: 'Labour Directorate',
    years_in_role: 5.0,
    interview_date: '15 Sep 2025',
    interview_time: '2:30 PM',
    location: 'Kampala',
    interviewer_id: 'usr-john-okello-001',
    interviewer_name: 'John Okello',
    tier: 'Management',
    status: 'In Progress',
    duration_min: 90,
    completion_percentage: 65,
    created_at: '2025-09-15T11:30:00Z',
    updated_at: '2025-09-15T13:00:00Z',
  },
  {
    id: 'int-003',
    interviewee_name: 'Patricia Namutebi',
    role_title: 'Manager, HR',
    department_unit: 'Employment Services',
    years_in_role: 4.2,
    interview_date: '14 Sep 2025',
    interview_time: '11:20 AM',
    location: 'Mbarara',
    interviewer_id: 'usr-john-okello-001',
    interviewer_name: 'John Okello',
    tier: 'Management',
    status: 'In Progress',
    duration_min: 60,
    completion_percentage: 45,
    created_at: '2025-09-14T08:20:00Z',
    updated_at: '2025-09-14T09:20:00Z',
  },
  {
    id: 'int-004',
    interviewee_name: 'James Ochieng',
    role_title: 'Frontline Officer',
    department_unit: 'Labour Office',
    years_in_role: 2.0,
    interview_date: '13 Sep 2025',
    interview_time: '4:10 PM',
    location: 'Gulu',
    interviewer_id: 'usr-john-okello-001',
    interviewer_name: 'John Okello',
    tier: 'Frontline',
    status: 'Draft',
    duration_min: 45,
    completion_percentage: 20,
    created_at: '2025-09-13T13:10:00Z',
    updated_at: '2025-09-13T13:55:00Z',
  },
  {
    id: 'int-005',
    interviewee_name: 'Agnes Nakato',
    role_title: 'IT Support',
    department_unit: 'Ministry of Gender',
    years_in_role: 3.0,
    interview_date: '12 Sep 2025',
    interview_time: '9:45 AM',
    location: 'Kampala',
    interviewer_id: 'usr-john-okello-001',
    interviewer_name: 'John Okello',
    tier: 'Support/IT',
    status: 'Completed',
    duration_min: 50,
    completion_percentage: 100,
    created_at: '2025-09-12T06:45:00Z',
    updated_at: '2025-09-12T07:35:00Z',
  },
  {
    id: 'int-006',
    interviewee_name: 'Fred Kato',
    role_title: 'HR Officer',
    department_unit: 'Employment Services',
    years_in_role: 6.5,
    interview_date: '11 Sep 2025',
    interview_time: '3:20 PM',
    location: 'Mbale',
    interviewer_id: 'usr-john-okello-001',
    interviewer_name: 'John Okello',
    tier: 'Frontline',
    status: 'Completed',
    duration_min: 65,
    completion_percentage: 100,
    created_at: '2025-09-11T12:20:00Z',
    updated_at: '2025-09-11T13:25:00Z',
  },
  {
    id: 'int-007',
    interviewee_name: 'Grace Ninsiima',
    role_title: 'Programme Officer',
    department_unit: 'Labour Directorate',
    years_in_role: 2.8,
    interview_date: '10 Sep 2025',
    interview_time: '1:15 PM',
    location: 'Fort Portal',
    interviewer_id: 'usr-john-okello-001',
    interviewer_name: 'John Okello',
    tier: 'Management',
    status: 'In Progress',
    duration_min: 60,
    completion_percentage: 55,
    created_at: '2025-09-10T10:15:00Z',
    updated_at: '2025-09-10T11:15:00Z',
  },
  {
    id: 'int-008',
    interviewee_name: 'Michael Ssemanda',
    role_title: 'System Administrator',
    department_unit: 'Ministry of Gender',
    years_in_role: 4.0,
    interview_date: '09 Sep 2025',
    interview_time: '10:40 AM',
    location: 'Kampala',
    interviewer_id: 'usr-john-okello-001',
    interviewer_name: 'John Okello',
    tier: 'Support/IT',
    status: 'Draft',
    duration_min: 45,
    completion_percentage: 25,
    created_at: '2025-09-09T07:40:00Z',
    updated_at: '2025-09-09T08:25:00Z',
  },
  // Remaining 4 interviews to total 12:
  {
    id: 'int-009',
    interviewee_name: 'Dr. Martin Mugisha',
    role_title: 'Commissioner OSH',
    department_unit: 'Department of OSH',
    years_in_role: 7.1,
    interview_date: '08 Sep 2025',
    interview_time: '11:00 AM',
    location: 'Jinja',
    interviewer_id: 'usr-john-okello-001',
    interviewer_name: 'John Okello',
    tier: 'Leadership',
    status: 'Completed',
    duration_min: 80,
    completion_percentage: 100,
    created_at: '2025-09-08T08:00:00Z',
    updated_at: '2025-09-08T09:20:00Z',
  },
  {
    id: 'int-010',
    interviewee_name: 'Ronald Baluku',
    role_title: 'Senior Labour Inspector',
    department_unit: 'Labour Office',
    years_in_role: 5.4,
    interview_date: '07 Sep 2025',
    interview_time: '2:15 PM',
    location: 'Kasese',
    interviewer_id: 'usr-john-okello-001',
    interviewer_name: 'John Okello',
    tier: 'Frontline',
    status: 'Completed',
    duration_min: 70,
    completion_percentage: 100,
    created_at: '2025-09-07T11:15:00Z',
    updated_at: '2025-09-07T12:25:00Z',
  },
  {
    id: 'int-011',
    interviewee_name: 'Beatrice Akello',
    role_title: 'Records Officer',
    department_unit: 'Ministry HQ Records',
    years_in_role: 3.2,
    interview_date: '06 Sep 2025',
    interview_time: '10:00 AM',
    location: 'Kampala',
    interviewer_id: 'usr-john-okello-001',
    interviewer_name: 'John Okello',
    tier: 'Frontline',
    status: 'Completed',
    duration_min: 55,
    completion_percentage: 100,
    created_at: '2025-09-06T07:00:00Z',
    updated_at: '2025-09-06T07:55:00Z',
  },
  {
    id: 'int-012',
    interviewee_name: 'Jane Nabukenya',
    role_title: 'Principal Legal Officer',
    department_unit: 'Industrial Relations & Dispute Resolution',
    years_in_role: 4.8,
    interview_date: '05 Sep 2025',
    interview_time: '3:00 PM',
    location: 'Kampala',
    interviewer_id: 'usr-john-okello-001',
    interviewer_name: 'John Okello',
    tier: 'Leadership',
    status: 'In Progress',
    duration_min: 65,
    completion_percentage: 70,
    created_at: '2025-09-05T12:00:00Z',
    updated_at: '2025-09-05T13:05:00Z',
  },
];

export const INITIAL_RECENT_ACTIVITIES: RecentActivityItem[] = [
  {
    id: 'act-1',
    description: 'You completed an interview at Ministry of Health',
    timestamp: '2 hours ago',
    type: 'completed',
    organisation: 'Ministry of Health',
  },
  {
    id: 'act-2',
    description: 'You started an interview at Labour Department',
    timestamp: '4 hours ago',
    type: 'started',
    organisation: 'Labour Department',
  },
  {
    id: 'act-3',
    description: 'A document was uploaded for Ministry of Gender',
    timestamp: '6 hours ago',
    type: 'document',
    organisation: 'Ministry of Gender',
  },
];

export const UPCOMING_SCHEDULE = [
  {
    id: 'sch-1',
    department: 'Labour Directorate',
    datetime: '16 Sep 2025 • 2:30 PM',
    tier: 'Management',
  },
  {
    id: 'sch-2',
    department: 'Employment Services',
    datetime: '17 Sep 2025 • 10:00 AM',
    tier: 'Frontline',
  },
  {
    id: 'sch-3',
    department: 'Ministry of Gender',
    datetime: '18 Sep 2025 • 9:00 AM',
    tier: 'Leadership',
  },
  {
    id: 'sch-4',
    department: 'Labour Department',
    datetime: '19 Sep 2025 • 11:30 AM',
    tier: 'Support/IT',
  },
];

export function createInitialChecklist(interviewId: string): DocumentItem[] {
  return STATUTORY_DOCUMENTS_CATALOGUE.map((doc, idx) => ({
    id: `doc-${interviewId}-${doc.item_number}`,
    interview_id: interviewId,
    item_number: doc.item_number,
    document_title: doc.document_title,
    category: doc.category,
    exists_status: idx < 5 ? 'Yes' : idx < 10 ? 'Partial' : 'Unknown',
    collected_status: idx < 3 ? 'Collected' : 'Pending',
    notes: idx === 0 ? 'Verified 2020-2025 strategic document from Registry.' : '',
    follow_up_action: idx >= 3 && idx < 6 ? 'Requested official copy from Commissioner OSH.' : '',
    file_name: idx < 2 ? `MGLSD_Doc_Ref_${doc.item_number}.pdf` : undefined,
    file_url: idx < 2 ? '#' : undefined,
  }));
}

export function createInitialNotes(interviewId: string): InterviewerNote {
  return {
    id: `note-${interviewId}`,
    interview_id: interviewId,
    observations: 'Interviewee was very forthcoming regarding systemic inspection constraints, transport logistics, and the dual reporting challenges faced by District Labour Officers.',
    numbers_captured: {
      total_staff: 142,
      labour_officers_count: 58,
      annual_inspections: 1240,
      disputes_logged: 890,
      disputes_resolved: 612,
      budget_allocated_ugx: '14.8 Billion UGX',
      budget_released_pct: 68,
      backlog_cases: 278,
    },
    contradictions: 'Reported 100% inspection coverage of factories in Kampala, but records indicate only 32% received follow-up compliance checks due to lack of fuel.',
    documents_collected_summary: 'Collected Strategic Plan, Draft OSH SOPs, and Q3 Inspection summary.',
    follow_ups: '1. Follow up with Undersecretary on vehicle maintenance budget vote.\n2. Obtain formal copy of EEMIS architecture review report.\n3. Request tripartite dispute logs from Industrial Court registrar.',
    maturity_signals: {
      governance_score: 3,
      technology_score: 2,
      process_score: 3,
      people_skills_score: 3,
      data_reporting_score: 2,
      justification: 'Strong institutional memory and legal statutory framework, but heavy reliance on manual paper records and critical shortages in field inspection mobility.',
    },
    updated_at: '2025-09-16T08:30:00Z',
  };
}

// Sample initial answers for Sarah Nansubuga (int-001)
export const SAMPLE_ANSWERS_INT_001: Answer[] = [
  {
    id: 'ans-001-A1',
    interview_id: 'int-001',
    question_id: 'A1',
    answer_text: 'The statutory mandate derives from the 1995 Constitution (Articles 40 and 32), the Employment Act 2006, the Occupational Safety and Health Act 2006, and the Labour Unions Act 2006. Our primary duty is to regulate the labour market, ensure decent work, protect workers from occupational hazards, mediate industrial disputes, and safeguard migrant workers. In practice, operational reality is heavily constrained by our limited field presence outside Kampala and the low ratio of Labour Officers to operating enterprises.',
    updated_at: '2025-09-16T07:30:00Z',
  },
  {
    id: 'ans-001-A2',
    interview_id: 'int-001',
    question_id: 'A2',
    answer_text: 'The National Employment Policy and NDPIII (Human Capital Development Programme) guide our Ministerial Policy Statements. We set annual inspection and dispute resolution targets, but budget ceilings set by MoFPED mean that discretionary non-wage operational releases only cover about 65% of planned field activities.',
    updated_at: '2025-09-16T07:45:00Z',
  },
  {
    id: 'ans-001-B1',
    interview_id: 'int-001',
    question_id: 'B1',
    answer_text: 'The current organogram has 3 main departments: Labour, Industrial Relations & Productivity; Occupational Safety & Health; and Employment Services. While theoretically sound, there is severe fragmentation in external employment vetting and dispute tracking. We need a dedicated digital command and intelligence unit to oversee cross-district compliance.',
    updated_at: '2025-09-16T08:00:00Z',
  },
  {
    id: 'ans-001-H1',
    interview_id: 'int-001',
    question_id: 'H1',
    answer_text: 'The single biggest systemic risk is the disconnect between central technical leadership and devolved District Labour Officers reporting to CAOs. District officers lack fuel, computers, and protective equipment. When workplace accidents or strikes occur, the Ministry is held politically responsible without having direct administrative control over the district staff.',
    updated_at: '2025-09-16T08:15:00Z',
  },
  {
    id: 'ans-001-H2',
    interview_id: 'int-001',
    question_id: 'H2',
    answer_text: 'In 3 years, under the TRANSFORMATIVE Programme, we envision a fully digitized Labour Inspectorate where every Labour Officer has a connected ruggedized tablet, real-time geo-tagged inspection filing, an automated dispute registry with SMS notifications for workers, and an integrated EEMIS portal linking embassies, recruiting agencies, and border immigration.',
    updated_at: '2025-09-16T08:25:00Z',
  },
  {
    id: 'ans-001-H3',
    interview_id: 'int-001',
    question_id: 'H3',
    answer_text: 'Top 3 quick wins: 1) Roll out standardized digital inspection checklists and mobile data collection; 2) Gazetting the revised Employment Regulations; 3) Establish an automated toll-free grievance and whistleblowing hotline linked directly to our central case management system.',
    updated_at: '2025-09-16T08:30:00Z',
  },
];
