/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Question, InterviewTier } from '../types';

export const MASTER_QUESTIONS: Question[] = [
  // SECTION A: STRATEGY, POLICY & MANDATE
  {
    id: 'A1',
    section_code: 'A',
    section_title: 'Section A: Strategy, Policy & Mandate',
    question_text: 'What is the statutory mandate of the Labour Directorate, and how effectively does current operational practice reflect this mandate?',
    who_to_ask: 'Minister, Permanent Secretary, Director of Labour, Commissioners',
    prompt_hints: 'Probe: Key enabling legislation (Employment Act 2006, OSH Act 2006, Labour Unions Act, Workers Compensation Act); gaps between legal mandate and actual daily operational scope; areas of mission creep or mandate neglect.',
    applicable_tiers: ['Leadership', 'Management'],
    response_type: 'text',
    sort_order: 1,
  },
  {
    id: 'A2',
    section_code: 'A',
    section_title: 'Section A: Strategy, Policy & Mandate',
    question_text: 'How are national policies (such as National Employment Policy, Decent Work Agenda, and NDPIII) translated into actionable departmental priorities?',
    who_to_ask: 'Permanent Secretary, Director, Commissioners, Assistant Commissioners',
    prompt_hints: 'Probe: Cascading process from Cabinet to Directorate; clarity of multi-year goals; role of Ministerial Policy Statements (MPS) in daily priority setting; alignment with Vision 2040.',
    applicable_tiers: ['Leadership', 'Management'],
    response_type: 'text',
    sort_order: 2,
  },
  {
    id: 'A3',
    section_code: 'A',
    section_title: 'Section A: Strategy, Policy & Mandate',
    question_text: 'What major gaps, inconsistencies, or outdated provisions exist in the current legal and regulatory framework governing labour in Uganda?',
    who_to_ask: 'Director of Labour, Commissioners, Legal Officer',
    prompt_hints: 'Probe: Status of draft amendments (e.g. Employment Amendment Bill); regulation of informal economy; modern forms of work (gig economy, remote work); adequacy of statutory penalties.',
    applicable_tiers: ['Leadership', 'Management'],
    response_type: 'text',
    sort_order: 3,
  },
  {
    id: 'A4',
    section_code: 'A',
    section_title: 'Section A: Strategy, Policy & Mandate',
    question_text: 'How does the Directorate track and diagnose labour market dynamics, youth unemployment trends, and sectoral labour shortages?',
    who_to_ask: 'Commissioner Employment Services, Principal Labour Economists, Statistics Focal Point',
    prompt_hints: 'Probe: Frequency of Labour Market Information System (LMIS) updates; reliance on UBOS surveys vs internal data; usage of data in policy design; feedback loops with employers.',
    applicable_tiers: ['Leadership', 'Management'],
    response_type: 'text',
    sort_order: 4,
  },
  {
    id: 'A5',
    section_code: 'A',
    section_title: 'Section A: Strategy, Policy & Mandate',
    question_text: 'What are the current top 3 strategic priorities or directives issued by Executive Leadership, and what progress has been achieved?',
    who_to_ask: 'Minister, Permanent Secretary, Director',
    prompt_hints: 'Probe: Externalisation of labour safeguards; decentralised inspection rollouts; digitization of services; presidential directives on industrial disputes; specific milestone targets.',
    applicable_tiers: ['Leadership', 'Management'],
    response_type: 'text',
    sort_order: 5,
  },
  {
    id: 'A6',
    section_code: 'A',
    section_title: 'Section A: Strategy, Policy & Mandate',
    question_text: 'How does the Labour Directorate coordinate with other Ministries, Departments, and Agencies (MDAs)—such as Internal Affairs/Immigration, Health, Justice, Education, and Local Government?',
    who_to_ask: 'Permanent Secretary, Director, Head of Units',
    prompt_hints: 'Probe: Inter-agency taskforces; data sharing protocols; institutional friction in issuing work permits; joint factory/site inspections; cross-jurisdictional referrals.',
    applicable_tiers: ['Leadership', 'Management'],
    response_type: 'text',
    sort_order: 6,
  },
  {
    id: 'A7',
    section_code: 'A',
    section_title: 'Section A: Strategy, Policy & Mandate',
    question_text: 'How is operational delivery coordinated between the central Ministry headquarters and the District Labour Offices (DLOs) under Local Government devolution?',
    who_to_ask: 'Director of Labour, Commissioner Labour & Industrial Relations, Principal Labour Officers',
    prompt_hints: 'Probe: Reporting lines between DLOs (reporting to Chief Administrative Officers - CAOs) and MGLSD technical oversight; inspection data transmission; supervision visits; logistical support.',
    applicable_tiers: ['Leadership', 'Management'],
    response_type: 'text',
    sort_order: 7,
  },
  {
    id: 'A8',
    section_code: 'A',
    section_title: 'Section A: Strategy, Policy & Mandate',
    question_text: 'What key performance indicators (KPIs) are currently used to evaluate the Directorate’s success, and how are these KPIs monitored and reported?',
    who_to_ask: 'Director of Labour, Planning Unit, Commissioners',
    prompt_hints: 'Probe: Output indicators (e.g. number of inspections, disputes resolved within 30 days, revenue collected); outcome indicators (fatal accidents reduction, compliance rates); frequency of performance reviews.',
    applicable_tiers: ['Leadership', 'Management'],
    response_type: 'text',
    sort_order: 8,
  },

  // SECTION B: INSTITUTIONAL STRUCTURE, GOVERNANCE & OVERSIGHT
  {
    id: 'B1',
    section_code: 'B',
    section_title: 'Section B: Institutional Structure, Governance & Oversight',
    question_text: 'Does the existing departmental and divisional organogram reflect the current workload, strategic priorities, and operational reality?',
    who_to_ask: 'Permanent Secretary, Director, Principal HR Officer',
    prompt_hints: 'Probe: Department of Labour, Industrial Relations & Productivity; Department of OSH; Department of Employment Services; statutory bodies; bottlenecks caused by current hierarchy.',
    applicable_tiers: ['Leadership', 'Management'],
    response_type: 'text',
    sort_order: 9,
  },
  {
    id: 'B2',
    section_code: 'B',
    section_title: 'Section B: Institutional Structure, Governance & Oversight',
    question_text: 'Are the mandates and division of responsibilities across departments and units clearly delineated, or do overlaps and silos exist?',
    who_to_ask: 'Commissioners, Assistant Commissioners, Heads of Unit',
    prompt_hints: 'Probe: Overlap between general labour inspection and OSH inspections; coordination between dispute settlement and Industrial Court; communication across units.',
    applicable_tiers: ['Leadership', 'Management'],
    response_type: 'text',
    sort_order: 10,
  },
  {
    id: 'B3',
    section_code: 'B',
    section_title: 'Section B: Institutional Structure, Governance & Oversight',
    question_text: 'What statutory boards, councils, or committees exist (e.g., Labour Advisory Board, OSH Board, Minimum Wages Board), and what is their operational status?',
    who_to_ask: 'Director, Commissioners, Board Secretariats',
    prompt_hints: 'Probe: Composition of boards; frequency of statutory meetings; budgetary allocations for sittings; implementation of board resolutions; tenure of current members.',
    applicable_tiers: ['Leadership', 'Management'],
    response_type: 'text',
    sort_order: 11,
  },
  {
    id: 'B4',
    section_code: 'B',
    section_title: 'Section B: Institutional Structure, Governance & Oversight',
    question_text: 'Describe the formal and informal reporting lines, supervisory cadence, and escalation pathways for critical issues.',
    who_to_ask: 'Heads of Department, Principal Officers',
    prompt_hints: 'Probe: Weekly/monthly management meetings; incident escalation (fatal workplace accidents, illegal wildcat strikes); speed of executive sign-offs.',
    applicable_tiers: ['Leadership', 'Management'],
    response_type: 'text',
    sort_order: 12,
  },
  {
    id: 'B5',
    section_code: 'B',
    section_title: 'Section B: Institutional Structure, Governance & Oversight',
    question_text: 'How are strategic management decisions made, minuted, and tracked through to completion within the Directorate?',
    who_to_ask: 'Director, Commissioners, Administrative Officers',
    prompt_hints: 'Probe: Action-item tracking systems; accountability for non-delivery; delegation of financial and operational authority thresholds.',
    applicable_tiers: ['Leadership', 'Management'],
    response_type: 'text',
    sort_order: 13,
  },
  {
    id: 'B6',
    section_code: 'B',
    section_title: 'Section B: Institutional Structure, Governance & Oversight',
    question_text: 'What internal audit, compliance, and ethical oversight mechanisms are in place to ensure integrity in inspections, licensing, and enforcement?',
    who_to_ask: 'Director, Internal Audit Focal Point, Commissioners',
    prompt_hints: 'Probe: Integrity management committee; inspector code of conduct; whistleblowing channels; audit recommendations implementation; handling of complaints against officers.',
    applicable_tiers: ['Leadership', 'Management'],
    response_type: 'text',
    sort_order: 14,
  },
  {
    id: 'B7',
    section_code: 'B',
    section_title: 'Section B: Institutional Structure, Governance & Oversight',
    question_text: 'What formal service standards or Client Service Charters exist, and are they measured and published?',
    who_to_ask: 'Commissioners, Quality Assurance / Client Charter Officer',
    prompt_hints: 'Probe: Turnaround times for dispute resolution, workplace registration, permit vetting, complaint acknowledgement; public visibility of standards.',
    applicable_tiers: ['Leadership', 'Management'],
    response_type: 'text',
    sort_order: 15,
  },
  {
    id: 'B8',
    section_code: 'B',
    section_title: 'Section B: Institutional Structure, Governance & Oversight',
    question_text: 'How effectively does the Directorate collaborate with external oversight bodies such as the IGG, Auditor General, and Parliament?',
    who_to_ask: 'Permanent Secretary, Director, Legal / Planning',
    prompt_hints: 'Probe: Timeliness of responses to parliamentary queries; implementation of Auditor General recommendations; compliance with regulatory scrutiny.',
    applicable_tiers: ['Leadership', 'Management'],
    response_type: 'text',
    sort_order: 16,
  },

  // SECTION C: OPERATIONAL DELIVERY & CORE WORKFLOWS
  {
    id: 'C1',
    section_code: 'C',
    section_title: 'Section C: Operational Delivery & Core Workflows',
    question_text: 'Provide a high-level overview of the Directorate’s core operational workflows from citizen/business intake to final resolution.',
    who_to_ask: 'Commissioners, Heads of Unit, Senior Labour Officers, Frontline Officers',
    prompt_hints: 'Probe: End-to-end journey for typical cases; manual paper steps vs digital steps; key hand-offs between departments or central vs district levels.',
    applicable_tiers: ['Management', 'Frontline'],
    response_type: 'text',
    sort_order: 17,
  },
  {
    id: 'C1a',
    section_code: 'C',
    section_title: 'Section C: Operational Delivery & Core Workflows',
    question_text: 'Detailed Labour Inspection Workflow: Describe the end-to-end process for scheduling, executing, reporting, and enforcing workplace inspections.',
    who_to_ask: 'Commissioner Labour, Principal Labour Officer (Inspections), District Labour Officers',
    prompt_hints: 'Probe: Risk-based vs random targeting; standard inspection checklists; issuance of Improvement/Prohibition Notices; prosecution of non-compliant employers; re-inspection rates.',
    applicable_tiers: ['Management', 'Frontline'],
    response_type: 'text',
    sort_order: 18,
  },
  {
    id: 'C1b',
    section_code: 'C',
    section_title: 'Section C: Operational Delivery & Core Workflows',
    question_text: 'Detailed Dispute Resolution & Reconciliation: Describe how labour disputes and individual complaints are received, recorded, mediated, and settled.',
    who_to_ask: 'Labour Officers (Disputes), Industrial Relations Officers, Conciliators',
    prompt_hints: 'Probe: Intake registry; mediation notice issuance; statutory 30-day timeline compliance; referral mechanisms to the Industrial Court; enforcement of settlement awards.',
    applicable_tiers: ['Management', 'Frontline'],
    response_type: 'text',
    sort_order: 19,
  },
  {
    id: 'C1c',
    section_code: 'C',
    section_title: 'Section C: Operational Delivery & Core Workflows',
    question_text: 'Detailed Work Permits & External Employment Vetting: Describe the vetting and clearance of Ugandan migrant workers and recruitment agencies (PRAs).',
    who_to_ask: 'Commissioner Employment Services, EEMIS Technical Team, Vetting Officers',
    prompt_hints: 'Probe: Agency pre-qualification; job order authentication; pre-departure training verification; clearance certificates; foreign mission coordination and repatriation protocols.',
    applicable_tiers: ['Management', 'Frontline'],
    response_type: 'text',
    sort_order: 20,
  },
  {
    id: 'C1d',
    section_code: 'C',
    section_title: 'Section C: Operational Delivery & Core Workflows',
    question_text: 'Detailed Occupational Safety & Health (OSH) Registration & Auditing: Describe the registration of workplaces, statutory examinations (boilers, cranes), and incident investigations.',
    who_to_ask: 'Commissioner OSH, OSH Inspectors, Occupational Hygienists, Statutory Examiners',
    prompt_hints: 'Probe: Workplace registration certificates; hazardous equipment certification; workplace injury reporting (Workers Compensation Form 1); fatal accident investigation protocols.',
    applicable_tiers: ['Management', 'Frontline'],
    response_type: 'text',
    sort_order: 21,
  },
  {
    id: 'C2',
    section_code: 'C',
    section_title: 'Section C: Operational Delivery & Core Workflows',
    question_text: 'What are the primary operational bottlenecks, case backlogs, or recurring failure points in these workflows?',
    who_to_ask: 'Frontline Labour Officers, Dispute Mediators, OSH Inspectors, Unit Heads',
    prompt_hints: 'Probe: Unresolved disputes backlog; uninspected high-risk factories; delays in vetting migrant contracts; lack of transport to follow up on compliance notices.',
    applicable_tiers: ['Management', 'Frontline'],
    response_type: 'text',
    sort_order: 22,
  },
  {
    id: 'C3',
    section_code: 'C',
    section_title: 'Section C: Operational Delivery & Core Workflows',
    question_text: 'What Standard Operating Procedures (SOPs), manuals, or statutory guidelines are available, and how consistently are they utilized in the field?',
    who_to_ask: 'Heads of Unit, Senior Labour Officers, Frontline Staff',
    prompt_hints: 'Probe: Date of last SOP review; availability in print/digital form; compliance variability across different officers or districts.',
    applicable_tiers: ['Management', 'Frontline'],
    response_type: 'text',
    sort_order: 23,
  },
  {
    id: 'C4',
    section_code: 'C',
    section_title: 'Section C: Operational Delivery & Core Workflows',
    question_text: 'What logistical and operational challenges affect field operations, on-site inspections, and evidence collection?',
    who_to_ask: 'Frontline Inspectors, District Labour Officers, Drivers/Logistics Focal',
    prompt_hints: 'Probe: Availability of inspection vehicles/fuel; personal protective equipment (PPE); testing instruments (sound meters, gas detectors, lux meters); camera/evidence handling.',
    applicable_tiers: ['Management', 'Frontline'],
    response_type: 'text',
    sort_order: 24,
  },
  {
    id: 'C5',
    section_code: 'C',
    section_title: 'Section C: Operational Delivery & Core Workflows',
    question_text: 'How does the Directorate gather citizen and enterprise feedback, handle public inquiries, and manage whistle-blower complaints?',
    who_to_ask: 'Public Relations Officer, Frontline Desk Officers, Complaints Desk',
    prompt_hints: 'Probe: Toll-free lines; walk-in customer care desk; digital complaint portal; anonymous whistle-blower protection; typical response times.',
    applicable_tiers: ['Management', 'Frontline'],
    response_type: 'text',
    sort_order: 25,
  },

  // SECTION D: HUMAN RESOURCES, STAFFING & CAPABILITY
  {
    id: 'D1',
    section_code: 'D',
    section_title: 'Section D: Human Resources, Staffing & Capability',
    question_text: 'What are the approved establishment numbers versus actual filled positions across the Directorate?',
    who_to_ask: 'Permanent Secretary, Director, Principal Human Resource Officer',
    prompt_hints: 'Probe: Total sanctioned posts; current vacancy rate percentage; critical shortages (e.g. specialized OSH chemical inspectors, actuaries, legal officers).',
    applicable_tiers: ['Leadership', 'Management'],
    response_type: 'text',
    sort_order: 26,
  },
  {
    id: 'D2',
    section_code: 'D',
    section_title: 'Section D: Human Resources, Staffing & Capability',
    question_text: 'What is the profile of technical skills, qualifications, and specialized competencies currently available within the staff body?',
    who_to_ask: 'Commissioners, Heads of Unit, Principal HR Officer',
    prompt_hints: 'Probe: Engineering, occupational hygiene, medicine, labour economics, dispute mediation credentials; gap in specialized digital or forensics capability.',
    applicable_tiers: ['Leadership', 'Management'],
    response_type: 'text',
    sort_order: 27,
  },
  {
    id: 'D3',
    section_code: 'D',
    section_title: 'Section D: Human Resources, Staffing & Capability',
    question_text: 'What structured training, continuous professional development, and onboarding programmes are provided to staff?',
    who_to_ask: 'Principal HR Officer, Commissioners, Frontline Officers',
    prompt_hints: 'Probe: Annual training budget; induction curriculum for new Labour Officers; international study tours (e.g. ILO ITC Turin); donor-funded training workshops.',
    applicable_tiers: ['Leadership', 'Management'],
    response_type: 'text',
    sort_order: 28,
  },
  {
    id: 'D4',
    section_code: 'D',
    section_title: 'Section D: Human Resources, Staffing & Capability',
    question_text: 'How are staff performance appraisals conducted, and how are targets linked to departmental performance agreements?',
    who_to_ask: 'Director, Commissioners, Principal HR Officer',
    prompt_hints: 'Probe: Public Service Commission appraisal tool; setting SMART inspection and mediation targets; reward and sanctions framework; frequency of appraisal reviews.',
    applicable_tiers: ['Leadership', 'Management'],
    response_type: 'text',
    sort_order: 29,
  },
  {
    id: 'D5',
    section_code: 'D',
    section_title: 'Section D: Human Resources, Staffing & Capability',
    question_text: 'What factors most significantly influence staff morale, retention, absenteeism, and career progression?',
    who_to_ask: 'Commissioners, Senior & Junior Labour Officers, HR',
    prompt_hints: 'Probe: Remuneration compared to other regulatory agencies (e.g. ERA, UCC); field allowances; safety risks in hostile inspection environments; career stagnation.',
    applicable_tiers: ['Leadership', 'Management'],
    response_type: 'text',
    sort_order: 30,
  },
  {
    id: 'D6',
    section_code: 'D',
    section_title: 'Section D: Human Resources, Staffing & Capability',
    question_text: 'How are District Labour Officers (DLOs) deployed, supervised, and supported technically by the central Directorate?',
    who_to_ask: 'Commissioner Labour, DLO Representatives, HR Officer',
    prompt_hints: 'Probe: Dual loyalty between Local Government District Councils and MGLSD; funding of DLO offices; joint inspection operations; technical secondments.',
    applicable_tiers: ['Leadership', 'Management'],
    response_type: 'text',
    sort_order: 31,
  },

  // SECTION E: INFORMATION SYSTEMS, TECHNOLOGY & DATA
  {
    id: 'E1',
    section_code: 'E',
    section_title: 'Section E: Information Systems, Technology & Data',
    question_text: 'What software applications, digital databases, or legacy systems are currently deployed across the Directorate?',
    who_to_ask: 'Head of ICT / Systems Administrator, Commissioners, Frontline Users',
    prompt_hints: 'Probe: EEMIS (External Employment Management Information System); OSH Information System; Labour Market Information System (LMIS); e-dispute tracker; spreadsheets.',
    applicable_tiers: ['Management', 'Frontline', 'Support/IT'],
    response_type: 'text',
    sort_order: 32,
  },
  {
    id: 'E2',
    section_code: 'E',
    section_title: 'Section E: Information Systems, Technology & Data',
    question_text: 'Comprehensive Assessment of EEMIS: How effective is the system in handling agency licensing, job orders, vetting, and migrant welfare monitoring?',
    who_to_ask: 'EEMIS System Administrator, Commissioner Employment, Verification Officers',
    prompt_hints: 'Probe: System uptime and reliability; user satisfaction; security and audit logs; employer/migrant worker portals; mobile responsiveness; integration with Gulf receiving states.',
    applicable_tiers: ['Management', 'Frontline', 'Support/IT'],
    response_type: 'text',
    sort_order: 33,
  },
  {
    id: 'E3',
    section_code: 'E',
    section_title: 'Section E: Information Systems, Technology & Data',
    question_text: 'What is the state of hardware infrastructure, workstation availability, network connectivity, and electrical power across headquarters and field stations?',
    who_to_ask: 'IT Support Officers, Records Officers, Frontline Staff',
    prompt_hints: 'Probe: Ratio of PCs/laptops to officers; LAN speed; National Data Backbone Network (NITA-U) connectivity stability; UPS/generator backup; field tablet availability.',
    applicable_tiers: ['Management', 'Frontline', 'Support/IT'],
    response_type: 'text',
    sort_order: 34,
  },
  {
    id: 'E4',
    section_code: 'E',
    section_title: 'Section E: Information Systems, Technology & Data',
    question_text: 'How are records and data collected, verified, archived, and secured against loss or unauthorized alteration?',
    who_to_ask: 'Principal Records Officer, ICT Security Officer, Frontline Clerks',
    prompt_hints: 'Probe: Paper registry vs electronic filing; physical registry storage conditions (dampness, fire protection, pest control); data backup frequency; offsite backups.',
    applicable_tiers: ['Management', 'Frontline', 'Support/IT'],
    response_type: 'text',
    sort_order: 35,
  },
  {
    id: 'E5',
    section_code: 'E',
    section_title: 'Section E: Information Systems, Technology & Data',
    question_text: 'What interoperability and data exchange mechanisms exist between the Directorate and external MDAs (NIRA, URA, Immigration, Police, UBOS)?',
    who_to_ask: 'Head of ICT, Systems Architects, Commissioners',
    prompt_hints: 'Probe: Direct API connections vs manual batch CSV imports; National ID (NIN) verification through NIRA; tax compliance verification through URA; immigration border clearance.',
    applicable_tiers: ['Management', 'Frontline', 'Support/IT'],
    response_type: 'text',
    sort_order: 36,
  },
  {
    id: 'E6',
    section_code: 'E',
    section_title: 'Section E: Information Systems, Technology & Data',
    question_text: 'What is the level of digital literacy, software adoption, and IT helpdesk support available to staff?',
    who_to_ask: 'IT Helpdesk Lead, End Users across Units',
    prompt_hints: 'Probe: Average time to resolve hardware/network tickets; resistance to digital forms; training needs on productivity and specialized software.',
    applicable_tiers: ['Management', 'Frontline', 'Support/IT'],
    response_type: 'text',
    sort_order: 37,
  },
  {
    id: 'E7',
    section_code: 'E',
    section_title: 'Section E: Information Systems, Technology & Data',
    question_text: 'How are analytical reports, statistical bulletins, and executive dashboards generated from operational data?',
    who_to_ask: 'Planning Unit, Statisticians, ICT Officers, Director',
    prompt_hints: 'Probe: Automated dashboard vs manual copy-pasting into Excel; time required to compile the Annual Labour Report; data accuracy and duplicate records.',
    applicable_tiers: ['Management', 'Frontline', 'Support/IT'],
    response_type: 'text',
    sort_order: 38,
  },

  // SECTION F: BUDGET, FINANCE & RESOURCE ALLOCATION
  {
    id: 'F1',
    section_code: 'F',
    section_title: 'Section F: Budget, Finance & Resource Allocation',
    question_text: 'What is the Directorate’s annual budgetary allocation under the Medium-Term Expenditure Framework (MTEF), broken down by Wage, Non-Wage Recurrent, and Development?',
    who_to_ask: 'Undersecretary / Accounting Officer, Principal Economist, Director, Commissioners',
    prompt_hints: 'Probe: Total UGX allocated across the three main departments; percentage of total Ministry budget; historical trend over past 3 fiscal years.',
    applicable_tiers: ['Management', 'Frontline'],
    response_type: 'text',
    sort_order: 39,
  },
  {
    id: 'F2',
    section_code: 'F',
    section_title: 'Section F: Budget, Finance & Resource Allocation',
    question_text: 'How timely and complete are quarterly warrant releases from the Ministry of Finance, Planning and Economic Development (MoFPED)?',
    who_to_ask: 'Principal Finance Officer, Planning Unit, Commissioners',
    prompt_hints: 'Probe: Budget cut frequencies; discrepancies between approved budget and actual quarterly releases; impact on scheduled field inspections and mediation hearings.',
    applicable_tiers: ['Management', 'Frontline'],
    response_type: 'text',
    sort_order: 40,
  },
  {
    id: 'F3',
    section_code: 'F',
    section_title: 'Section F: Budget, Finance & Resource Allocation',
    question_text: 'What proportion of operational and capital activities depends on Development Partner / Donor funding (e.g., ILO, IOM, Enabel, World Bank)?',
    who_to_ask: 'Project Coordinators, Planning Unit, Commissioners',
    prompt_hints: 'Probe: Active donor projects; sustainability when donor projects phase out; alignment of donor deliverables with core Directorate mandates.',
    applicable_tiers: ['Management', 'Frontline'],
    response_type: 'text',
    sort_order: 41,
  },
  {
    id: 'F4',
    section_code: 'F',
    section_title: 'Section F: Budget, Finance & Resource Allocation',
    question_text: 'What Non-Tax Revenue (NTR) is generated through Directorate activities (e.g. workplace registrations, statutory examination fees, PRA licensing), and what is the collection mechanism?',
    who_to_ask: 'Principal Cashier / Accounts, OSH Registrars, Employment Services Licensing Desk',
    prompt_hints: 'Probe: Annual NTR targets vs actual collections; URA e-Tax portal integration; revenue leakage risks; retention vs 100% remittance to Consolidated Fund.',
    applicable_tiers: ['Management', 'Frontline'],
    response_type: 'text',
    sort_order: 42,
  },
  {
    id: 'F5',
    section_code: 'F',
    section_title: 'Section F: Budget, Finance & Resource Allocation',
    question_text: 'What are the most severe financial constraints currently hindering day-to-day statutory operations?',
    who_to_ask: 'Commissioners, Heads of Department, Frontline Officers',
    prompt_hints: 'Probe: Fuel votes; witness summoning fees; night allowance for field officers; printing of statutory certificates and inspection forms; vehicle maintenance debt.',
    applicable_tiers: ['Management', 'Frontline'],
    response_type: 'text',
    sort_order: 43,
  },

  // SECTION G: STAKEHOLDER ENGAGEMENT & SOCIAL DIALOGUE
  {
    id: 'G1',
    section_code: 'G',
    section_title: 'Section G: Stakeholder Engagement & Social Dialogue',
    question_text: 'How structured, regular, and effective are tripartite consultations with the Federation of Uganda Employers (FUE) and Labour Federations (NOTU / COFTU)?',
    who_to_ask: 'Minister, Director, Commissioner Labour & Industrial Relations',
    prompt_hints: 'Probe: Functioning of National Tripartite Council; negotiations on minimum wage; resolution of national industrial disputes; collective bargaining agreement (CBA) registrations.',
    applicable_tiers: ['Leadership', 'Management', 'Support/IT'],
    response_type: 'text',
    sort_order: 44,
  },
  {
    id: 'G2',
    section_code: 'G',
    section_title: 'Section G: Stakeholder Engagement & Social Dialogue',
    question_text: 'How does the Directorate engage with informal economy workers, domestic worker associations, and vulnerable labour segments?',
    who_to_ask: 'Commissioner Employment, Principal Labour Officers, Civil Society Focal',
    prompt_hints: 'Probe: Engagement with market vendors, boda boda associations; formalization initiatives; awareness of basic rights; addressing child labour in agriculture and mining.',
    applicable_tiers: ['Leadership', 'Management', 'Support/IT'],
    response_type: 'text',
    sort_order: 45,
  },
  {
    id: 'G3',
    section_code: 'G',
    section_title: 'Section G: Stakeholder Engagement & Social Dialogue',
    question_text: 'What is the nature of engagement, compliance monitoring, and association dialogue with Private Recruitment Agencies (e.g., UAERA)?',
    who_to_ask: 'Commissioner Employment Services, Licensing Officers, PRA Monitoring Desk',
    prompt_hints: 'Probe: Quarterly consultative forums; compliance audits; dispute arbitration between agencies and returnee migrant workers; handling of unlicensed recruitment brokers.',
    applicable_tiers: ['Leadership', 'Management', 'Support/IT'],
    response_type: 'text',
    sort_order: 46,
  },
  {
    id: 'G4',
    section_code: 'G',
    section_title: 'Section G: Stakeholder Engagement & Social Dialogue',
    question_text: 'How does the Directorate manage international and regional labour commitments with the ILO, East African Community (EAC), and bilateral labour agreements (BLAs)?',
    who_to_ask: 'Director, Legal Advisory Unit, International Labour Affairs Desk',
    prompt_hints: 'Probe: Reporting on ratified ILO Conventions (e.g., C81, C155); negotiation and enforcement of Bilateral Labour Agreements with Gulf destinations; EAC common market labour mobility.',
    applicable_tiers: ['Leadership', 'Management', 'Support/IT'],
    response_type: 'text',
    sort_order: 47,
  },
  {
    id: 'G5',
    section_code: 'G',
    section_title: 'Section G: Stakeholder Engagement & Social Dialogue',
    question_text: 'What public sensitization, worker rights education, and employer compliance campaigns are conducted?',
    who_to_ask: 'Public Relations Officer, Labour Inspectors, Outreach Focal',
    prompt_hints: 'Probe: Radio talk shows in regional languages; World Day for Safety and Health at Work; distribution of labour law primers; workplace poster distributions.',
    applicable_tiers: ['Leadership', 'Management', 'Support/IT'],
    response_type: 'text',
    sort_order: 48,
  },
  {
    id: 'G6',
    section_code: 'G',
    section_title: 'Section G: Stakeholder Engagement & Social Dialogue',
    question_text: 'How does the Directorate manage media inquiries, public scandals (e.g. stranded migrant workers abroad, factory disasters), and crisis communication?',
    who_to_ask: 'Minister, Permanent Secretary, Principal Communications Officer, Director',
    prompt_hints: 'Probe: Standard media protocols; coordination with Uganda missions abroad; official press statements vs unauthorized leaks; public trust management.',
    applicable_tiers: ['Leadership', 'Management', 'Support/IT'],
    response_type: 'text',
    sort_order: 49,
  },

  // SECTION H: STRATEGIC CHALLENGES, VISION & PRIORITY REFORMS
  {
    id: 'H1',
    section_code: 'H',
    section_title: 'Section H: Strategic Challenges, Vision & Priority Reforms',
    question_text: 'From your perspective, what are the single biggest systemic risks or institutional vulnerabilities currently facing the Labour Directorate?',
    who_to_ask: 'All Interviewees (Leadership, Management, Frontline, Support/IT)',
    prompt_hints: 'Probe: Operational collapse risks; reputational damage; staff burnout; technological obsolescence; corruption risks; policy paralysis.',
    applicable_tiers: ['Leadership', 'Management', 'Frontline', 'Support/IT'],
    response_type: 'text',
    sort_order: 50,
  },
  {
    id: 'H2',
    section_code: 'H',
    section_title: 'Section H: Strategic Challenges, Vision & Priority Reforms',
    question_text: 'If you had full authority and targeted resources, what would the Labour Directorate look like in 3 years under a transformative modernization programme?',
    who_to_ask: 'All Interviewees (Leadership, Management, Frontline, Support/IT)',
    prompt_hints: 'Probe: Digital transformation vision; inspection reach and enforcement power; staffing profile and dignity of labour officers; regional/district footprint; citizen satisfaction.',
    applicable_tiers: ['Leadership', 'Management', 'Frontline', 'Support/IT'],
    response_type: 'text',
    sort_order: 51,
  },
  {
    id: 'H3',
    section_code: 'H',
    section_title: 'Section H: Strategic Challenges, Vision & Priority Reforms',
    question_text: 'What are the top 3 high-impact, immediate reforms or "quick wins" that should be executed within the next 3 to 6 months?',
    who_to_ask: 'All Interviewees (Leadership, Management, Frontline, Support/IT)',
    prompt_hints: 'Probe: Pragmatic low-cost improvements; critical policy statutory instrument gazetting; workflow simplification; quick digital fixes; staff welfare/equipment provision.',
    applicable_tiers: ['Leadership', 'Management', 'Frontline', 'Support/IT'],
    response_type: 'text',
    sort_order: 52,
  },

  // SYSTEM WALKTHROUGH (W1 - W4) for Support/IT Tier
  {
    id: 'W1',
    section_code: 'W',
    section_title: 'System Access Walkthrough',
    question_text: 'Live Demonstration: Core Application Access & Authentication Walkthrough (Log into primary system, show user roles, MFA, session management)',
    who_to_ask: 'System Administrator / IT Specialist / Records Manager',
    prompt_hints: 'Observe: Screen-share or direct demonstration of EEMIS / OSH system login, role-based screens, password policies, multi-factor authentication (if any), timeout mechanisms.',
    applicable_tiers: ['Support/IT'],
    response_type: 'structured',
    sort_order: 53,
  },
  {
    id: 'W2',
    section_code: 'W',
    section_title: 'System Access Walkthrough',
    question_text: 'Live Demonstration: Transaction Processing & Database Architecture (Submit a test transaction, show database schema, table indexing, and data validation rules)',
    who_to_ask: 'Database Administrator / Senior Developer / Systems Analyst',
    prompt_hints: 'Observe: Step through creating a record (e.g. PRA license application or workplace inspection filing); verify frontend validation; check database writes; observe foreign key constraints and error handling.',
    applicable_tiers: ['Support/IT'],
    response_type: 'structured',
    sort_order: 54,
  },
  {
    id: 'W3',
    section_code: 'W',
    section_title: 'System Access Walkthrough',
    question_text: 'Live Demonstration: Backup, Disaster Recovery & Network Reliability (Show actual backup routines, storage location, restoration testing, and NITA-U bandwidth monitoring)',
    who_to_ask: 'Infrastructure Engineer / Network Admin / IT Security Officer',
    prompt_hints: 'Observe: Automated vs manual backup scripts; offsite replication; timestamp of last successful disaster recovery dry-run; network utilization graphs.',
    applicable_tiers: ['Support/IT'],
    response_type: 'structured',
    sort_order: 55,
  },
  {
    id: 'W4',
    section_code: 'W',
    section_title: 'System Access Walkthrough',
    question_text: 'Live Demonstration: User Provisioning, Access Control & Audit Trails (Walk through onboarding an officer, assigning permissions, and viewing system event logs)',
    who_to_ask: 'System Administrator / Security Lead',
    prompt_hints: 'Observe: User lifecycle management; deprovisioning of departed officers; review of audit log entries (who viewed/edited sensitive migrant or enterprise inspection files).',
    applicable_tiers: ['Support/IT'],
    response_type: 'structured',
    sort_order: 56,
  },
];

// The 20 Statutory Supporting Documents Checklist items
export const STATUTORY_DOCUMENTS_CATALOGUE = [
  {
    item_number: 1,
    document_title: 'MGLSD Strategic Plan (2020/21–2024/25)',
    category: 'Strategic & Policy',
  },
  {
    item_number: 2,
    document_title: 'Approved Ministerial Policy Statement (MPS) (Current FY)',
    category: 'Strategic & Policy',
  },
  {
    item_number: 3,
    document_title: 'Approved Staff Structure / Organogram & Staff Establishment List',
    category: 'Human Resources & Governance',
  },
  {
    item_number: 4,
    document_title: 'National Employment Policy & Implementation Action Plan',
    category: 'Strategic & Policy',
  },
  {
    item_number: 5,
    document_title: 'Occupational Safety and Health (OSH) Policy & Guidelines',
    category: 'Operational Guidelines',
  },
  {
    item_number: 6,
    document_title: 'External Employment Regulations & Statutory Instruments (SI No. 62/2021)',
    category: 'Legal & Regulatory',
  },
  {
    item_number: 7,
    document_title: 'Standard Operating Procedures (SOPs) for Labour Inspections',
    category: 'Operational Guidelines',
  },
  {
    item_number: 8,
    document_title: 'Standard Operating Procedures (SOPs) for Dispute Resolution & Mediation',
    category: 'Operational Guidelines',
  },
  {
    item_number: 9,
    document_title: 'EEMIS Technical Architecture, System Specifications & User Manuals',
    category: 'Information Systems',
  },
  {
    item_number: 10,
    document_title: 'Annual Directorate Performance Report (Previous FY)',
    category: 'Reporting & Monitoring',
  },
  {
    item_number: 11,
    document_title: 'Departmental Work Plans & Procurement Plans (Current FY)',
    category: 'Planning & Finance',
  },
  {
    item_number: 12,
    document_title: 'Labour Inspection Register / Logbook (Official extract)',
    category: 'Operational Records',
  },
  {
    item_number: 13,
    document_title: 'Industrial Court / Labour Disputes Register & Case Hearing Log',
    category: 'Operational Records',
  },
  {
    item_number: 14,
    document_title: 'Private Recruitment Agencies (PRA) Licensing Register & Vetting Records',
    category: 'Operational Records',
  },
  {
    item_number: 15,
    document_title: 'Non-Tax Revenue (NTR) Collection Statements (Last 2 FYs)',
    category: 'Planning & Finance',
  },
  {
    item_number: 16,
    document_title: 'Ministry ICT Strategy & Information Security Policy',
    category: 'Information Systems',
  },
  {
    item_number: 17,
    document_title: 'Tripartite Charter & National Tripartite Council Minutes (Last 2 sittings)',
    category: 'Stakeholder & Governance',
  },
  {
    item_number: 18,
    document_title: 'District Labour Officers (DLO) Inspection Summary Reports',
    category: 'Operational Records',
  },
  {
    item_number: 19,
    document_title: 'Internal Audit Reports relating to Labour Directorate (Last 2 FYs)',
    category: 'Reporting & Monitoring',
  },
  {
    item_number: 20,
    document_title: 'Development Partner Project Agreements & Subvention MoUs (Active programmes)',
    category: 'Strategic & Policy',
  },
];

/**
 * Filter questions based on selected tier
 * Tier routing rules:
 * - Leadership → A, B, D, G, H
 * - Management → A (context), B, C, D, E, F, G, H
 * - Frontline Staff → C, E, F, H
 * - Support / IT / Records → E, G, H + W1–W4
 */
export function getQuestionsForTier(tier: InterviewTier): Question[] {
  return MASTER_QUESTIONS.filter((q) => q.applicable_tiers.includes(tier));
}

export function getSectionsForTier(tier: InterviewTier): { code: string; title: string; count: number }[] {
  const questions = getQuestionsForTier(tier);
  const sectionMap = new Map<string, { code: string; title: string; count: number }>();

  for (const q of questions) {
    if (!sectionMap.has(q.section_code)) {
      sectionMap.set(q.section_code, {
        code: q.section_code,
        title: q.section_title,
        count: 0,
      });
    }
    sectionMap.get(q.section_code)!.count++;
  }

  return Array.from(sectionMap.values());
}
